api_platform:
    title: 'BilMo'
    description: 'Main API for BilMo app.'
    version: 1.0.0
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header