@startuml
'https://plantuml.com/class-diagram

class User {
    + username: String
    + email: String
}
class Client {
    + username: String
    + email: String
    + password: String
}
class Product {
    + name: String
    + price: Float
}

Client "1" o- "*" User
Client "1..*" o-- "*" Product
User "*" - "*" Product


@enduml