@startuml
'https://plantuml.com/class-diagram

class User {
    + username: String
    + email: String
}
class Client {
    + email: String
    + password: String
}
class Product {
    + name: String
    + brand: String
    + price: Int
}

Client "*" o- "*" User
Client "*" o-- "*" Product
User "*" - "*" Product


@enduml
