controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
  resource: ../src/Kernel.php
  type: annotation

auth:
    path: /login_check
    methods: ['POST']
